apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.targetPort }}
  type: {{ .Values.serviceType }}
